"""add accepted_terms and banned_emails

Revision ID: 0f9c4eaa82a1
Revises: 8a493bf1f344
Create Date: 2026-05-01 21:26:25.335216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9c4eaa82a1'
down_revision = '8a493bf1f344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('banned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banned_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banned_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banned_emails_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_banned_emails_phone'), ['phone'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_terms', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('terms_accepted_at')
        batch_op.drop_column('accepted_terms')

    with op.batch_alter_table('banned_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banned_emails_phone'))
        batch_op.drop_index(batch_op.f('ix_banned_emails_email'))

    op.drop_table('banned_emails')
    # ### end Alembic commands ###
