"""add_status_submitted_by_to_market_prices

Revision ID: 31d39fdf5f25
Revises: 088a6c8eb1c5
Create Date: 2026-06-29 11:15:00.814517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d39fdf5f25'
down_revision = '088a6c8eb1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='approved'))
        batch_op.create_foreign_key(None, 'users', ['submitted_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('submitted_by_id')

    # ### end Alembic commands ###
