"""add is_deleted reply_to_id to messages

Revision ID: 4fbd0f4eed9a
Revises: c07b850d1b86
Create Date: 2026-06-16 21:39:32.055608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fbd0f4eed9a'
down_revision = 'c07b850d1b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crop_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('market', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('price_tzs', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('recorded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=100), nullable=True))
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'crops', ['crop_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('avg_price')
        batch_op.drop_column('crop_name')
        batch_op.drop_column('month')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('crop_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('avg_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('region',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('source')
        batch_op.drop_column('recorded_at')
        batch_op.drop_column('unit')
        batch_op.drop_column('price_tzs')
        batch_op.drop_column('market')
        batch_op.drop_column('crop_id')

    # ### end Alembic commands ###
