"""add edited_at and edited_by_id to partnerships

Revision ID: c344588a7336
Revises: fbebe9257182
Create Date: 2026-07-05 17:28:34.491136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c344588a7336'
down_revision = 'fbebe9257182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partnerships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edited_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['edited_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partnerships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('edited_by_id')
        batch_op.drop_column('edited_at')

    # ### end Alembic commands ###
