"""add partnerships table

Revision ID: fbebe9257182
Revises: 31d39fdf5f25
Create Date: 2026-07-02 13:13:36.912904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbebe9257182'
down_revision = '31d39fdf5f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partnerships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=150), nullable=False),
    sa.Column('organization_type', sa.String(length=20), nullable=False),
    sa.Column('interest_type', sa.String(length=20), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=150), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partnerships')
    # ### end Alembic commands ###
